fix: change router nat config for manual ips (#5629)
I cannot apply the terraform changes in #5536 because the existing NAT
router applies to all IPs:
```
Error: Error creating RouterNat: googleapi: Error 400: Invalid value for field 'resource.nats[0].sourceSubnetworkIpRangesToNat': 'ALL_SUBNETWORKS_ALL_IP_RANGES'. Can not create new Nats since a Nat with option ALL_SUBNETWORKS_ALL_IP_RANGES exists., invalid
```

I think changing this to just the specific subnetwork is okay (it at
least doesn't trigger a deletion), but I may revert this before release
if something on the test instance breaks.