Trial removal of --non_gcp
This seems to be where the need for exported service account keys stems
from by the looks of the logs:

ERROR: If --non_gcp is specified, --service_account_key has to be
specified, or GOOGLE_APPLICATION_CREDENTIALS has to set in os