fix(build): revert Cloud SDK pin for Debian converter
The switch from `google/cloud-sdk:449.0.0-alpine` to
`gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine` was not a
drop-in replacement:

This moved from Alpine 3.18.4 to 3.20.2 and 3.20.2 is more intolerant of
the `pip install poetry==1.8.3` being performed:

```
error: externally-managed-environment
```